- name: Deploy MongoDB
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - aws
    - mongo_3_0
    - munin_node
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
